/* A packrat parser generated by PackCC 1.2.0 */

#ifndef PCC_INCLUDED__PARSER_H
#define PCC_INCLUDED__PARSER_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct calc_context_tag calc_context_t;

calc_context_t *calc_create(void *auxil);
int calc_parse(calc_context_t *ctx, int *ret);
void calc_destroy(calc_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* PCC_INCLUDED__PARSER_H */
